#!/usr/bin/env python
"""Reload each saved checkpoint from disk and recompute its test metric.

The assignment says the reported metrics will be checked against the model and against a
replica of it, so the reported number has to be a property of the *checkpoint*, not of the
process that happened to produce it. This script closes that loop: it loads the saved
weights and tokenizer, runs the held-out split again, and compares against the number in
results/<task>/<run_id>.json. Writes docs/model_checks.md.

    python scripts/verify_models.py                 # the delivered model of each task
    python scripts/verify_models.py --all           # every saved checkpoint
    python scripts/verify_models.py --task ner pos
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
import torch

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from transformers import (AutoTokenizer, DataCollatorForTokenClassification,  # noqa: E402
                          DataCollatorWithPadding, Trainer, TrainingArguments)

from src import qa_utils  # noqa: E402
from src.common import MODELS, get_device, precision_flags  # noqa: E402
from src.data import load_task  # noqa: E402
from src.encoding import tokenize_task  # noqa: E402
from src.train import load_run_model  # noqa: E402
from src.metrics import (decode_token_predictions, ner_metrics, pos_metrics,  # noqa: E402
                         sequence_metrics, squad_metrics)
from src.report_data import HEADLINE, best_per_task, rows  # noqa: E402

TOLERANCE = 1e-4     # anything above this is a real difference, not MPS/CUDA non-determinism


def evaluate_checkpoint(task: str, path: Path, eval_batch_size: int = 64) -> dict:
    """Re-score a checkpoint.

    The batch size matters: padding is per batch, so a different grouping changes the shapes
    the matmuls see and, under reduced precision, moves a logit in the last decimal. That is
    enough to flip a near-tied answer span. Re-checking with the batch size the run actually
    used keeps the comparison exact instead of forcing a looser tolerance.
    """
    device = get_device()
    td = load_task(task)
    tokenizer = AutoTokenizer.from_pretrained(str(path))
    args = TrainingArguments(output_dir="/tmp/verify",
                             per_device_eval_batch_size=eval_batch_size,
                             report_to=[], **precision_flags(),
                             dataloader_num_workers=0,
                             label_names=(["start_positions", "end_positions"]
                                          if td.kind == "qa" else None))
    if td.kind == "qa":
        model = load_run_model("qa", str(path))
        feats = td.splits["test"].map(
            lambda ex: qa_utils.prepare_validation_features(ex, tokenizer), batched=True,
            remove_columns=td.splits["test"].column_names, desc="qa features")
        model_in = feats.remove_columns(["example_id", "offset_mapping"])
        trainer = Trainer(model=model, args=args, data_collator=DataCollatorWithPadding(tokenizer),
                          processing_class=tokenizer)
        raw = trainer.predict(model_in).predictions
        preds = qa_utils.postprocess_qa(td.splits["test"], feats, raw)
        return squad_metrics(preds, td.splits["test"])

    model = load_run_model(td.kind, str(path))
    tok = tokenize_task(td, tokenizer)
    collator = (DataCollatorWithPadding(tokenizer) if td.kind == "sequence"
                else DataCollatorForTokenClassification(tokenizer))
    trainer = Trainer(model=model, args=args, data_collator=collator, processing_class=tokenizer)
    out = trainer.predict(tok["test"])
    if td.kind == "sequence":
        return sequence_metrics(out.label_ids, np.argmax(out.predictions, axis=-1), td.labels)
    true_seqs, pred_seqs = decode_token_predictions(out.predictions, out.label_ids, td.labels)
    return ner_metrics(true_seqs, pred_seqs) if task == "ner" else pos_metrics(
        true_seqs, pred_seqs, td.labels)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--all", action="store_true", help="every saved checkpoint, not just delivered")
    ap.add_argument("--task", nargs="*")
    args = ap.parse_args()

    if args.all:
        targets = [r for r in rows() if (MODELS / r["task"] / r["run_id"]).exists()]
    else:
        targets = list(best_per_task().values())
    if args.task:
        targets = [r for r in targets if r["task"] in args.task]

    lines = ["# Checkpoint checks", "",
             "Every saved checkpoint is reloaded from disk and its held-out metric recomputed, so "
             "the number in the report is a property of the published weights rather than of the "
             "run that produced them. Generated by `scripts/verify_models.py`.", "",
             "| Task | Run | Metric | Reported | Recomputed | Δ | Eval batch |",
             "|---|---|---|---:|---:|---:|---:|"]
    failures = checked = 0
    for r in targets:
        path = MODELS / r["task"] / r["run_id"]
        if not path.exists():
            print(f"[skip] {r['task']}/{r['run_id']}: no checkpoint on disk", file=sys.stderr)
            continue
        key, name = HEADLINE[r["task"]]
        reported = r["raw"]["metrics"][key]
        hp = r["raw"].get("hyperparams", {})
        bs = hp.get("eval_batch_size") or (hp.get("batch_size", 32) * 2)
        got = evaluate_checkpoint(r["task"], path, eval_batch_size=bs)[key]
        delta = abs(got - reported)
        ok = delta <= TOLERANCE
        failures += not ok
        checked += 1
        mark = "" if ok else " ❌"
        scale = 100 if r["task"] != "qa" else 1
        lines.append(f"| {r['task']} | `{r['run_id']}` | {name} | {reported * scale:.3f} | "
                     f"{got * scale:.3f} | {delta * scale:.4f}{mark} | {bs} |")
        print(f"{'OK  ' if ok else 'FAIL'} {r['task']:7s} {r['run_id']:42s} "
              f"{name} reported={reported * scale:.3f} recomputed={got * scale:.3f}")

    lines += ["", f"Tolerance {TOLERANCE}. Each checkpoint is re-scored with the evaluation batch "
                  "size its own run used: padding is per batch, so a different grouping changes the "
                  "shapes the matmuls see and, in reduced precision, can move a logit enough to flip "
                  "a near-tied answer span. Reductions on GPU/MPS are not bit-exact either, so the "
                  "last decimal is allowed to move.", "",
              f"**{checked - failures}/{checked} checkpoints reproduce their reported metric.**"]
    (ROOT / "docs" / "model_checks.md").write_text("\n".join(lines) + "\n")
    print(f"\n[written] docs/model_checks.md — {checked - failures}/{checked} reproduce")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
